version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh:latest
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514/udp"
      - "1515:1515"
      - "514/udp"
      - "55000:55000"
    networks:
      - wazuh-elk
    volumes:
      - wazuh-data:/var/ossec/data

  logstash:
    image: wazuh/wazuh-logstash:latest
    hostname: logstash
    restart: always
    command: -f /etc/logstash/conf.d/
    ports:
      - "5000:5000"
    networks:
      - wazuh-elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/templates:/etc/logstash/templates

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - wazuh-elk
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    hostname: kibana
    ports:
      - "5601:5601"
    networks:
      - wazuh-elk
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config:/usr/share/kibana/config

networks:
  wazuh-elk:
    driver: bridge

volumes:
  wazuh-data:
  es-data:
